site_name: LibreCAD User Documentation
site_url: https://www.librecad.org/
site_description: Project documentation with Markdown.
site_author: LibreCAD Document Team

repo_url: https://github.com/GSStnb/docs
repo_name: GitHub

nav:
    - Home: ./Manual/Index.md
