site_name: LibreCAD User Documentation
site_url: https://www.librecad.org/
site_description: Project documentation with Markdown.
site_author: LibreCAD Document Team

repo_url: https://github.com/GSStnb/docs
repo_name: GitHub
edit_uri: ""

nav:
    - Home: ./Manual/Index.md
    - Reference Manual:
        - Installation: ./Manual/reference/Install.md
        - Configuration: ./Manual/reference/configuration.md
    - User Guide:
        - Printing: h./Manual/owto/PrintingGuide.md
     - Appendices:
        - Fonts: 
        - Release Notes: ./Manual/other/release-notes.md
        - Contributing: ./Manual/other/contributing.md
        - License: ./Manual/other/license.md

docs_dir: /manual/
