site_name: LibreCAD User Documentation

nav:
    - 'index.md'
#    - 'License':
- Reference:
    - 'Installation': ./reference/Install.md
    - 'The Coordinate system': ./reference/Coordinates.md
    - 'Tools': 'refTools.md'
- Users Guides:
    - 'Printing Guide': ./howto/PrintingGuide.md
#- Appendices:
#    - Fonts
#    - Contributing
#    - 
#    - 
    
# Release Notes

theme: readthedocs

docs_dir: manual
#site_dir: /html/
