site_name: LibreCAD User Documentation

nav:
    - Home: index.md
        - Installation: refInstall.md
        - The Coordinate system: refCoordinates.md
        - Menu: refMenu.md
        - Tools: refTools.md
    - Users Guides:
        - Printing Guide: /guides/Printing.md
    - Appendices:
        - Fonts: /appx/Fonts.md

#    - Contributing
#    - Release Notes
#    - License:


theme: readthedocs

docs_dir: manual
#site_dir: /html/
